### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by Kayra** [Dinkers/The-Curation#13]
Need to come up with a git workflow that doesn't block when there are pending PRs. Will come up with something and propose it here.

**Comment by Kayra** [comment]
Decided this isn't worth spending time on, I think we are moving quickly enough that we can just use main. If there are no objections @RobbyCowell I'll close this until it becomes a bigger problem

**Comment by RobbyCowell** [comment]
Agreed. MOVE FAST AND BREAK GIT
