### ISSUE TITLE
Build `/filters` endpoint

### ISSUE THREAD

**Issue by RobbyCowell** [Dinkers/The-Curation#6]
## Description
It would be great to have an endpoint: `/filters` that returns an aggregated list of the `specialty`s and `key_info`s of the places in the selected city. This endpoint would be used to populate the 'Filters' section of the Home screen.

![image](https://user-images.githubusercontent.com/3612297/118734134-941f9b00-b7f2-11eb-9c45-9b70993f2d34.png)

It would also be great to have the ability to associate each 'Filter' (`specialty` and `key_info`) with an image to use as a BG for each Filter element in the Filters section of the Home Screen.

## Requirements
1. Create an endpoint that returns an aggregated list of key_infos and specialties, given a city id (or name)
2. **For discussion** Make `specialty` and `key_info` into their own entity with the ability to add an image to each one.

    - We could also just create an entity called Filter (or something like 'attribute' etc.) and have something like this:
    ```
   {
     name: 'Vegan',
     type: 'key_info'
     image: '{id/url}'
   }
    ```

**Comment by RobbyCowell** [comment]
I think I'm going to handle this on the front-end instead. It should be a pretty trivial algo compared to rolling out a whole new endpoint to extract these filters.

**Comment by Kayra** [comment]
If you think it'll be quick and easy, feel free, but I think it's worth implementing on the backend for performance, small request inefficiencies aren't a big deal (can implement GraphQL when they are) but it feels like you'd be getting a lot of wasted info to build the filters in the client

**Comment by RobbyCowell** [comment]
OK, let's stick with an endpoint then.

I'm imagining something like: `/filters/{city-id}` which would return a list of results like the example above:

```
{
 name: 'Vegan',
 type: 'key_info'
 image: '{id/url}'
}
```

**Comment by Kayra** [comment]
Sounds good, will expose an endpoint that gives you all the usps and vital infos if no id is provided, and can narrow it down by city as you said. No image as we discussed in the other issue

**Comment by RobbyCowell** [comment]
Perfect!
