### ISSUE TITLE
Data types discussion

### ISSUE THREAD

**Issue by RobbyCowell** [Dinkers/The-Curation#8]
Let's focus the discussion around data types here.

### Fields (Places)
 - `opening_times` it would be good to ultimately have an `opening_times` data structure that contains open/close hours for each day of the week.
 - `contact_info` IMO it would be good to parse these out into separate fields (phone, email, IG, etc. b/c I'm lazy)
 - `key_info` should be an array (or array-like structure) *
 - `speciality` same deal as `key_info` *
 - Make `specialty` and `key_info` into their own entity with the ability to add an image to each one. ([see req 2 here](https://github.com/Dinkers/The-Curation/issues/6))

**Comment by Kayra** [comment]
Great suggestions on the fields, working on this in a [branch](https://github.com/Dinkers/The-Curation/tree/f/place-data-types). 

Current thoughts:
1. Will follow industry best practices for `opening_times` and `contact_info`
2. Will split out `key_info` and `speciality` but thinking of changing the names to `vital_info` and `USP` for more specificity and clarity
3. Want to push back on images for `key_info` and `speciality`, the ideal solution for me is for the client to server static image assets for vital infos and usps globally, I can create a script (or end-point if we need) that exposes the current unique values for each field, and we can add images as needed

@RobbyCowell - Let me know what you think about 2/3, your response is not blocking so no rush.

**Comment by Kayra** [comment]
@RobbyCowell Also what are your thoughts on address? Keep as textfield or do something fancier? 

Relevant resources:
- [https://pypi.org/project/django-address/](https://pypi.org/project/django-address/)
- [https://www.mjt.me.uk/posts/falsehoods-programmers-believe-about-addresses/](https://www.mjt.me.uk/posts/falsehoods-programmers-believe-about-addresses/)

**Comment by RobbyCowell** [comment]
Sounds good on the `opening_times` and `contact_info` approaches. I'd be interested in what the industry best practices are for `opening_times` as I've implemented an approach in another app I'm building and want to compare!

I'm happy with the name changes for `key_info` and `specialty`.

Statically hosted images sound good to me, and will probably be faster. I have a question about the approach though: how would we handle managing the `key_info` and `speciality` images through the admin tool, if at all? Maybe we could just keep like a static map of each entity and its respective images solely on the front-end?

Something like this for example:
```
// vital_info_image_map.json
vital_info: [
  {
    name: "Vegan"
    image: "/path/to/image"
  }
]
```

**Comment by Kayra** [comment]
Yeah that was what I was thinking of. Images on the front-end, with a placeholder for filters without an image, and a set of filters exposed by the backend (as per the other issue). That way you get a dynamic set of filters, and map the images to them on the front-end, and we can have a process for checking once a day/week/month for new filters that don't have bespoke images yet.

**Comment by RobbyCowell** [comment]
Sounds good, let's go for this approach then!
